version: '3'
services:
  db:
    image: apache-spark
    environment:
      - CASSANDRA_PASSWORD=banco
    ports:
      - '5432:5432'
    volumes:
      - '.:/home'
  cache:
    image: 'bitnami/redis:4.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
  app:
    build:
      context: .
    volumes:
      - '.:/java'
    ports:
      - '80:3000'
    depends_on:
      - db
      - cache
    command: 'spark -t 8:32 -b tcp://0.0.0.0:3000 -w 2'

    environment:
      REDIS_URL: 'redis://redis:6379/0'
